# Generated by Django 4.1 on 2022-12-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nic', models.TextField()),
                ('epfNumber', models.TextField()),
                ('telephone', models.IntegerField()),
                ('address', models.TextField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employeerole')),
            ],
        ),
    ]
