# Generated by Django 4.1 on 2022-12-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nic', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('maritial_status', models.TextField()),
                ('emloyee_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Resigned')], default=1)),
                ('image', models.ImageField(default='static/img/employees/default.jpg', upload_to='static/img/employees/')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employees.employee')),
                ('bank', models.TextField()),
                ('branch', models.TextField()),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employees.employee')),
                ('telephone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayrollInfo',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employees.employee')),
                ('epf_number', models.TextField()),
                ('joined_date', models.DateField()),
                ('basic_salary', models.IntegerField()),
                ('allowance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employeerole'),
        ),
    ]
