# Generated by Django 4.1 on 2022-12-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='epfNumber',
            new_name='epf_number',
        ),
    ]
