# Generated by Django 4.1 on 2022-12-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_epfnumber_employee_epf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emloyee_status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Resigned')], default=1),
        ),
    ]
