# Generated by Django 4.1 on 2022-12-28 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_employee_created_at_employee_created_by_employeelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employees.employee')),
                ('casual', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('annual', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('medical', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('monthly', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('annually', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('no_pay', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('epf_liable_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxable_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('epf_deduction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('advance_deduction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contribution_12', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contribution_3', models.DecimalField(decimal_places=2, max_digits=7)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('no_pay', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('epf_liable_salary', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('taxable_salary', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('epf_deduction', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('advance_deduction', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('contribution_12', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('contribution_3', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Leave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.leave')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
        ),
    ]
