# Generated by Django 4.1 on 2022-12-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeleavebalance_leave_payslip_payroll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_by',
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.payroll'),
        ),
    ]
