# Generated by Django 4.1 on 2022-12-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('created_date', models.DateField()),
                ('target_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Success'), (2, 'Failed'), (3, 'Dropped')], default=0)),
            ],
        ),
    ]
