# Generated by Django 4.1 on 2022-12-23 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
