# Generated by Django 4.1 on 2022-12-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.SmallIntegerField()),
                ('ledger_credit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit', to='accounts.ledger')),
                ('ledger_debit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit', to='accounts.ledger')),
            ],
        ),
    ]
