# Generated by Django 4.1 on 2022-12-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.ledger')),
                ('trial_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trialbalance')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='trial_balance_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.trialbalanceledger'),
        ),
    ]
