# Generated by Django 4.1 on 2022-12-28 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_created_at_account_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
