# Generated by Django 4.1 on 2022-10-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice_products',
            new_name='invoice_product',
        ),
    ]
