# Generated by Django 4.1 on 2022-10-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('inventory', '0002_rename_invoice_products_invoice_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='import_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('products_count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('load_status', models.SmallIntegerField()),
                ('payment_status', models.SmallIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='import_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('total', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.import_invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product')),
            ],
        ),
    ]
