# Generated by Django 4.1 on 2022-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_import_invoice_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_invoice',
            name='invoice_image',
            field=models.ImageField(default='static/img/invoices/default.jpg', upload_to='static/img/invoices/'),
        ),
    ]
