# Generated by Django 4.1 on 2022-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_import_invoice_invoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_invoice',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='load_status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='payment_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
