# Generated by Django 4.1 on 2022-12-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('inventory', '0006_import_invoice_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='import_invoice',
            new_name='ImportInvoice',
        ),
        migrations.RenameModel(
            old_name='invoice_product',
            new_name='ImportProduct',
        ),
        migrations.RenameModel(
            old_name='import_product',
            new_name='InvoiceProduct',
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice'),
        ),
    ]
