# Generated by Django 4.1 on 2022-12-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_import_invoice_importinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproduct',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.importinvoice'),
        ),
    ]
