# Generated by Django 4.1 on 2022-12-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_importproduct_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='importinvoice',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
