# Generated by Django 4.1 on 2022-12-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.IntegerField()),
                ('date', models.DateField()),
                ('bank', models.TextField()),
                ('account_number', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('image', models.ImageField(default='static/img/cheques/default.jpg', upload_to='static/img/cheques/')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Passed'), (2, 'Returned'), (3, 'Reissued')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
        ),
    ]
