# Generated by Django 4.1 on 2022-12-28 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_remove_cheque_customer_cheque_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
