# Generated by Django 4.1 on 2022-12-28 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0003_alter_cheque_created_at_alter_cheque_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cheques.cheque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
