# Generated by Django 4.1 on 2022-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_chequelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='remarks',
            field=models.TextField(),
        ),
    ]
