# Generated by Django 4.1 on 2022-12-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('connected_date', models.DateField(blank=True, default=None, null=True)),
                ('disconnected_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
