# Generated by Django 4.1 on 2022-12-28 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0003_utility_created_at_utility_created_by_utilitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilityinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilityinvoice',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
